### ISSUE TITLE
[Crunchyroll] If the show couldn't be clearly identified (asking if its e.g. Symphogear "G" or "GX"), the choice reappears after every page reload / episode switch

### ISSUE THREAD

**Issue by JannisBecker** [leonekmi/anilist-scrobbler#1]
So I was watching [Symphogear G](http://www.crunchyroll.com/symphogear/episode-1-the-gungnir-girl-685227) on Crunchyroll
and in the beginning I was asked if I was watching Symphogear G or GX, which is fine,
but I got the question over and over again after every switch to the next episode (and thus, new page loads). 
If it was possible, I think it would be nice to remember this choice somehow. 
Of course, remembering that could be a problem as soon as I start watching [Symphogear GX](http://www.crunchyroll.com/symphogear/episode-1-murderer-of-miracles-683489) (being the next season), right after it. 
Perhaps you could solve it in such a way that, as soon as the user is given a choice between anime names and chooses one, remember not just the answer but the given choices as well, and as soon as the user gets to the next episode, which triggers the identification again, if the scrobbler finds the same two anime names again and would be about to ask the exact same question once more, just don't do that and use the last choice again.
In my scenario, this would work all the way up to the last episode of Symphogear G, and as soon as I'd switch to Symphogear GX, the scrobbler would only find one anime named like that anyway, or at least certainly a different list of possible anime names than last time, and could then ask the user again, if neccessary.

**Comment by leonekmi** [comment]
I am working on a workaround : a choose cache (destroy at browser closing).
