### ISSUE TITLE
[Crunchyroll] Extension crashes while watching Gintama

### ISSUE THREAD

**Issue by JannisBecker** [leonekmi/anilist-scrobbler#3]
You can test this here, for example: http://www.crunchyroll.com/gintama/episode-138-why-not-talk-about-the-old-days-for-a-change-516254

For me, after the site loads, it correctly shows the anilist scrobbler popup but it doesn't go any further than
"Anilist Scrobbler : Starting...".

I also get the following messages (and errors) in the console: 
![chrome dev console](http://push.anukthewolf.com/files/a/chrome_2018-02-23_00-22-22.png)

The particular error being thrown in this line of code:
![error in code](http://push.anukthewolf.com/files/a/chrome_2018-02-23_00-24-14.png)

**Comment by leonekmi** [comment]
This issue was already patched in c10b7a5fe508fec1abec74095f92b4c066a73d72 but i forgot to deploy update, now it's okay, update in CWS should be live in minutes (you can force update by activating Developer Mode in Extensions menu and click "Update"). Firefox version is also updated.
